import { StyleSheet } from 'react-native';

const PALETTE = {
  redOrange: '#fa462f',
  cinder: '#0e0f16',
  white: '#fff',
  blue: '#9C6DFF',
  gray: '#383b40',
  gray2: '#686B71',
  green: '#0CC884',
  grayBorder: '#4F5258',
  grayBorder50: 'rgba(79, 82, 88, 0.5)',
  lightGray: '#88898C',
  shuttleGray: '#606266',
  white60: 'rgba(255, 255, 255, 0.6)',
  white05: 'rgba(255,255,255, 0.05)',
  trout: '#525466',
  redRibbon: '#e50539',
  black: '#000',
  dark4: '#383B40',
  scorpion: '#5C5C5C',
  waterloo: '#83859a',
  waterloo40: 'rgba(131, 133, 154, 0,4)',
  santasGray: '#9FA0A8',
  bombay: '#AFB1B3',
  shark: '#303136',
  bittersweet: '#FD605B',
  matterhorn: '#513D41',
  mako: '#42454A',
  kabul: '#564F3E',
  yellowMetal: '#78663C',
  darkShark: '#25262C',
  apple: '#3CD22E',
  inputErrorBg: 'rgba(182, 69, 69, 0.2)',
  acceptedStatusBg: 'rgba(10, 126, 0, 0.15)',
  acceptedStatusBorder: 'rgba(10, 126, 0, 0.2)',
  pendingStatusBg: 'rgba(255, 194, 51, 0.15)',
  pendingStatusBorder: 'rgba(255, 194, 51, 0.2)',
  rejectedStatusBg: 'rgba(250, 70, 47, 0.15)',
  rejectedStatusBorder: 'rgba(250, 70, 47, 0.2)',
  darkestShark: '#1A1B21',
  tertiary: '#1B1C22',
  silverChalice: '#a8a8a8',
  heliotrope: '#9c6dff',
  charade: '#2b2d37',
  electricViolet: '#9202ce',
  tamarind: '#3d1a1b',
  vividViolet: '#853094',
  deepCove: '#06094E',
  persianBlue: '#2329B5',
  sunglow: '#FFC233',
};

export const FONTS = {
  mainFont: 'Century Gothic',
  mainFontBold: 'CenturyGothic-Bold',
};

export const COLORS = {
  ACCEPTED_STATUS_BG: PALETTE.acceptedStatusBg,
  ACCEPTED_STATUS_BORDER: PALETTE.acceptedStatusBorder,
  PENDING_STATUS_BG: PALETTE.pendingStatusBg,
  PENDING_STATUS_BORDER: PALETTE.pendingStatusBorder,
  REJECTED_STATUS_BG: PALETTE.rejectedStatusBg,
  REJECTED_STATUS_BORDER: PALETTE.rejectedStatusBorder,
  FIRST_DEPOSIT_START_GRADIENT_BG: PALETTE.vividViolet,
  FIRST_DEPOSIT_END_GRADIENT_BG: PALETTE.deepCove,
  PRIMARY: PALETTE.redOrange,
  OUTLINE: PALETTE.redOrange,
  BLUE: PALETTE.blue,
  GREEN: PALETTE.green,
  ON_PRIMARY: PALETTE.white,
  BACKGROUND: PALETTE.cinder,
  MIDDLE_BACKGROUND: PALETTE.shark,
  INPUT_ERROR_BG: PALETTE.inputErrorBg,
  TERTIARY: PALETTE.tertiary,
  LIGHT_BACKGROUND: PALETTE.gray,
  LIGHTEST_BACKAGROUND: PALETTE.mako,
  TEXT_LIGHT: PALETTE.white,
  TEXT_MIDDLE: PALETTE.silverChalice,
  GRAY_BORDER: PALETTE.grayBorder,
  GRAY_BORDER_50: PALETTE.grayBorder50,
  GRAY_BACKGROUND: PALETTE.charade,
  DARK4: PALETTE.dark4,
  LIGHT_GRAY_BORDER: PALETTE.gray,
  TEXT_DARK: PALETTE.trout,
  TEXT_DANGER: PALETTE.bittersweet,
  WHITE: PALETTE.white,
  WHITE_60: PALETTE.white60,
  WHITE_05: PALETTE.white05,
  ACTIVE_TEXT: PALETTE.redRibbon,
  AVIATOR_BACKGROUND: PALETTE.redRibbon,
  BLACK: PALETTE.black,
  PLACEHOLDER: PALETTE.scorpion,
  BORDER_LIGHT: PALETTE.white,
  BORDER_ACTIVE: PALETTE.redOrange,
  DRAWER_ICON: PALETTE.waterloo,
  GRAY_SEPARATOR: PALETTE.shuttleGray,
  TEXT_GRAY: PALETTE.waterloo,
  TEXT_GRAY2: PALETTE.bombay,
  DRAG_LINE: PALETTE.santasGray,
  PLACEHOLDER_LIGHT: PALETTE.bombay,
  DANGER_BACKGROUND: PALETTE.matterhorn,
  ATTENTION_BACKGROUND: PALETTE.kabul,
  ATTENTION_BORDER: PALETTE.yellowMetal,
  OPTIONS_BACKGROUND: PALETTE.darkShark,
  BONUS_BACKGROUND: PALETTE.darkShark,
  TOURNAMENT_BACKGROUND: PALETTE.darkShark,
  GRAY2: PALETTE.gray2,
  SUCCESS: PALETTE.apple,
  DARK_BACKGROUND: PALETTE.darkestShark,
  HELIOTROPE_BACKGROUND: PALETTE.heliotrope,
  CRAZY_TIME_BANNER_BG: PALETTE.electricViolet,
  TAMARIND_SEPARATOR: PALETTE.tamarind,
  PERSIAN_BLUE: PALETTE.persianBlue,
  SUNGLOW: PALETTE.sunglow,
};

export const GUTTER_SIZE = 4;

export const SPACING = {
  XS: 4,
  S: 8,
  M: 12,
  L: 16,
  XL: 20,
  XXL: 32,
};

export const BUTTONS_HEIGHTS = { MEDIUM: 32, DEFAULT: 48 };
export const BUTTONS_WIDTHS = { MEDIUM: 64, DEFAULT: '100%' };

export const TEXT_VARIANTS = StyleSheet.create({
  font10: {
    fontFamily: FONTS.mainFont,
    fontSize: 10,
    color: COLORS.TEXT_LIGHT,
  },
  font10Bold: {
    fontFamily: FONTS.mainFontBold,
    fontSize: 10,
    color: COLORS.TEXT_LIGHT,
  },
  font12: {
    fontFamily: FONTS.mainFont,
    fontSize: 12,
    lineHeight: 16,
    color: COLORS.TEXT_LIGHT,
    textTransform: 'uppercase',
  },
  font12Bold: {
    fontFamily: FONTS.mainFontBold,
    fontSize: 12,
    color: COLORS.TEXT_LIGHT,
    textTransform: 'uppercase',
  },
  font14: {
    fontFamily: FONTS.mainFont,
    fontSize: 14,
    color: COLORS.TEXT_LIGHT,
  },
  font14Bold: {
    fontFamily: FONTS.mainFontBold,
    fontSize: 14,
  },
  font16: {
    fontFamily: FONTS.mainFont,
    fontSize: 16,
  },
  font18: {
    fontFamily: FONTS.mainFont,
    color: COLORS.TEXT_LIGHT,
    fontSize: 18,
  },
  font18Bold: {
    fontFamily: FONTS.mainFontBold,
    color: COLORS.TEXT_LIGHT,
    fontSize: 18,
  },
  font20: {
    fontFamily: FONTS.mainFont,
    fontSize: 20,
  },
  font20Bold: {
    fontFamily: FONTS.mainFontBold,
    color: COLORS.TEXT_LIGHT,
    textTransform: 'uppercase',
    fontSize: 20,
  },
  font22Bold: {
    fontFamily: FONTS.mainFontBold,
    fontSize: 22,
    color: COLORS.TEXT_LIGHT,
  },
  font16Bold: {
    fontFamily: FONTS.mainFontBold,
    fontSize: 16,
  },
  font24: {
    fontFamily: FONTS.mainFont,
    fontSize: 24,
    color: COLORS.TEXT_LIGHT,
    textTransform: 'uppercase',
  },
  font24Bold: {
    fontFamily: FONTS.mainFontBold,
    fontSize: 24,
    lineHeight: 32,
    color: COLORS.TEXT_LIGHT,
  },
  font28: {
    fontFamily: FONTS.mainFont,
    fontSize: 28,
    color: COLORS.TEXT_LIGHT,
    textTransform: 'uppercase',
  },
  font32: {
    fontFamily: FONTS.mainFontBold,
    fontSize: 32,
    color: COLORS.TEXT_LIGHT,
    textTransform: 'uppercase',
  },
  font58Bold: {
    fontFamily: FONTS.mainFontBold,
    fontSize: 58,
    color: COLORS.TEXT_LIGHT,
    textTransform: 'uppercase',
  },
});

export const DRAWER_ICON_MARGIN_LEFT = 6;
